#!/usr/bin/env python3
# Copyright (c) Meta Platforms, Inc. and affiliates.
"""
Multi-object 3D scene reconstruction using custom masks.

Adapted from demo_scene_reconstruction.py to work with masks generated by
extract_objects/step1_segment_sam3.py

Usage:
    cd /mnt/hdd/scenes/sam-3d-objects
    conda run -n sam3d-objects python demo_custom_masks.py \
        --image ../generations/Flux2_00013_.png \
        --masks-dir ../output/20260116_124849/masks \
        --output-dir ../output/20260116_124849/sam3d_demo
"""
import sys
import os
import gc
import json
import argparse
from datetime import datetime
import numpy as np
import torch
import trimesh
from copy import deepcopy
from PIL import Image

# Add notebook to path for inference utilities
sys.path.append("notebook")
from inference import (
    Inference,
    load_image,
    make_scene,
    ready_gaussian_for_video_rendering,
)

# Import transformation utilities from SAM 3D Objects
from pytorch3d.transforms import quaternion_to_matrix
from sam3d_objects.data.dataset.tdfy.transforms_3d import compose_transform


def load_masks_from_metadata(masks_dir):
    """
    Load masks from a directory with metadata.json (step1 format).

    Returns:
        List of binary mask arrays
    """
    metadata_path = os.path.join(masks_dir, "metadata.json")
    with open(metadata_path) as f:
        metadata = json.load(f)

    masks = []
    for mask_info in metadata['masks']:
        mask_path = os.path.join(masks_dir, mask_info['filename'])
        mask_img = np.array(Image.open(mask_path))

        # Extract alpha channel as binary mask
        if mask_img.ndim == 3:
            mask = mask_img[..., 3] > 127
        else:
            mask = mask_img > 127

        masks.append(mask)

    return masks, metadata


def clear_gpu_memory():
    """Clear GPU cache and run garbage collection."""
    gc.collect()
    torch.cuda.empty_cache()


def move_output_to_cpu(output, keep_gaussian=True):
    """Move output tensors to CPU to free GPU memory."""
    cpu_output = {}

    for key in ['rotation', 'translation', 'scale']:
        if key in output and output[key] is not None:
            if keep_gaussian:
                cpu_output[key] = output[key].clone()
            else:
                cpu_output[key] = output[key].cpu().clone()

    if 'mesh' in output and output['mesh'] is not None:
        mesh_result = output['mesh'][0]
        cpu_output['mesh_vertices'] = mesh_result.vertices.cpu().clone()
        cpu_output['mesh_faces'] = mesh_result.faces.cpu().clone()

    if 'glb' in output and output['glb'] is not None:
        cpu_output['glb'] = output['glb']

    if keep_gaussian and 'gaussian' in output and output['gaussian'] is not None:
        cpu_output['gaussian'] = output['gaussian']

    return cpu_output


def transform_mesh_preserve_visual(mesh, rotation_quat, translation, scale, yup_to_zup):
    """
    Transform a mesh while preserving its visual (texture or vertex colors).
    """
    vertices_yup = np.array(mesh.vertices, dtype=np.float32)
    vertices_zup = vertices_yup @ yup_to_zup

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    vertices_tensor = torch.tensor(vertices_zup, dtype=torch.float32).to(device)
    rotation_quat = rotation_quat.to(device)
    translation = translation.to(device)
    scale = scale.to(device)

    R_l2c = quaternion_to_matrix(rotation_quat)
    l2c_transform = compose_transform(scale=scale, rotation=R_l2c, translation=translation)
    transformed = l2c_transform.transform_points(vertices_tensor.unsqueeze(0)).squeeze(0)
    transformed_np = transformed.cpu().numpy()

    new_mesh = trimesh.Trimesh(
        vertices=transformed_np,
        faces=mesh.faces.copy(),
        process=False
    )

    if hasattr(mesh.visual, 'uv') and mesh.visual.uv is not None:
        new_mesh.visual = mesh.visual.copy()
    elif hasattr(mesh.visual, 'vertex_colors') and mesh.visual.vertex_colors is not None:
        new_mesh.visual.vertex_colors = mesh.visual.vertex_colors.copy()

    return new_mesh


def sample_texture_to_vertex_colors(mesh):
    """Convert a textured mesh to use vertex colors."""
    if not hasattr(mesh.visual, 'uv') or mesh.visual.uv is None:
        return None

    uvs = mesh.visual.uv
    material = mesh.visual.material

    texture = None
    if hasattr(material, 'baseColorTexture') and material.baseColorTexture is not None:
        texture = np.array(material.baseColorTexture)
    elif hasattr(material, 'image') and material.image is not None:
        texture = np.array(material.image)

    if texture is None:
        return None

    h, w = texture.shape[:2]
    u = np.clip(uvs[:, 0], 0, 1)
    v = np.clip(uvs[:, 1], 0, 1)
    px = (u * (w - 1)).astype(int)
    py = ((1 - v) * (h - 1)).astype(int)

    if texture.ndim == 2:
        colors = texture[py, px]
        colors = np.stack([colors, colors, colors, np.full_like(colors, 255)], axis=-1)
    elif texture.shape[2] == 3:
        colors = texture[py, px]
        alpha = np.full((colors.shape[0], 1), 255, dtype=np.uint8)
        colors = np.concatenate([colors, alpha], axis=-1)
    else:
        colors = texture[py, px]

    return colors.astype(np.uint8)


def merge_trimeshes(meshes):
    """Combine multiple trimesh objects into a single mesh."""
    if not meshes:
        return None

    all_vertices = []
    all_faces = []
    all_colors = []
    vertex_offset = 0

    for mesh in meshes:
        all_vertices.append(mesh.vertices)
        all_faces.append(mesh.faces + vertex_offset)

        if hasattr(mesh.visual, 'vertex_colors') and mesh.visual.vertex_colors is not None:
            all_colors.append(mesh.visual.vertex_colors)

        vertex_offset += len(mesh.vertices)

    combined = trimesh.Trimesh(
        vertices=np.vstack(all_vertices),
        faces=np.vstack(all_faces),
        process=False
    )

    if len(all_colors) == len(meshes):
        combined.visual.vertex_colors = np.vstack(all_colors)

    return combined


def main():
    parser = argparse.ArgumentParser(description="SAM-3D-Objects scene reconstruction with custom masks")
    parser.add_argument("--image", required=True, help="Path to input image")
    parser.add_argument("--masks-dir", required=True, help="Directory with masks and metadata.json")
    parser.add_argument("--output-dir", required=True, help="Output directory")
    parser.add_argument("--max-objects", type=int, default=None, help="Limit number of objects")
    parser.add_argument("--skip-gaussian", action="store_true", help="Skip Gaussian scene (saves memory)")
    args = parser.parse_args()

    os.makedirs(args.output_dir, exist_ok=True)
    output_prefix = os.path.join(args.output_dir, "scene")

    print("=" * 60)
    print("Multi-Object 3D Scene Reconstruction (Custom Masks)")
    print("=" * 60)
    print(f"\nImage: {args.image}")
    print(f"Masks: {args.masks_dir}")
    print(f"Output: {args.output_dir}/")

    # Load model
    print("\n[1/5] Loading SAM 3D Objects model...")
    inference = Inference("checkpoints/hf/pipeline.yaml", compile=False)

    # Load image and masks
    print("\n[2/5] Loading image and masks...")
    image = load_image(args.image)
    masks, metadata = load_masks_from_metadata(args.masks_dir)

    if args.max_objects is not None:
        masks = masks[:args.max_objects]
        metadata['masks'] = metadata['masks'][:args.max_objects]

    print(f"  Image shape: {image.shape}")
    print(f"  Number of objects: {len(masks)}")
    for i, m in enumerate(metadata['masks']):
        print(f"    {i}: {m['label']} (score={m['score']:.3f})")

    # Create individual objects directory
    individual_dir = os.path.join(args.output_dir, "objects_individual")
    os.makedirs(individual_dir, exist_ok=True)

    # Reconstruct each object
    print("\n[3/5] Reconstructing objects...")
    outputs = []
    failed_objects = []

    for i, mask in enumerate(masks):
        label = metadata['masks'][i]['label']
        print(f"  Processing {i}: {label}...", end=" ", flush=True)

        try:
            rgba = inference.merge_mask_to_rgba(image, mask)
            output = inference._pipeline.run(
                rgba,
                None,
                seed=42,
                stage1_only=False,
                with_mesh_postprocess=True,
                with_texture_baking=True,
                with_layout_postprocess=False,
                use_vertex_color=False,
            )

            # Save individual object
            if output.get("gs") is not None:
                output["gs"].save_ply(os.path.join(individual_dir, f"{i:02d}_{label}.ply"))
            if output.get("glb") is not None:
                output["glb"].export(os.path.join(individual_dir, f"{i:02d}_{label}.glb"))

            # Save pose
            pose_data = {
                'rotation': output['rotation'].cpu().numpy().tolist(),
                'translation': output['translation'].cpu().numpy().tolist(),
                'scale': output['scale'].cpu().numpy().tolist(),
            }
            with open(os.path.join(individual_dir, f"{i:02d}_{label}_pose.json"), 'w') as f:
                json.dump(pose_data, f, indent=2)

            output_cpu = move_output_to_cpu(output, keep_gaussian=not args.skip_gaussian)
            outputs.append(output_cpu)

            t = output_cpu['translation'].cpu().numpy().flatten()
            s = output_cpu['scale'].cpu().numpy().flatten()[0]
            print(f"pos=[{t[0]:.2f}, {t[1]:.2f}, {t[2]:.2f}], scale={s:.3f}")

            del output
            clear_gpu_memory()

        except torch.cuda.OutOfMemoryError:
            print(f"OOM - skipping")
            failed_objects.append(i)
            clear_gpu_memory()
        except Exception as e:
            print(f"ERROR: {e}")
            failed_objects.append(i)

    if failed_objects:
        print(f"\n  Warning: {len(failed_objects)} objects failed: {failed_objects}")

    # Create combined Gaussian splat scene
    print("\n[4/5] Combining Gaussian splats...")
    if args.skip_gaussian:
        print("  Skipped (--skip-gaussian)")
    else:
        try:
            outputs_with_gs = [o for o in outputs if o.get("gaussian") is not None]
            if outputs_with_gs:
                scene_gs = make_scene(*deepcopy(outputs_with_gs))
                scene_gs.save_ply(f"{output_prefix}_posed.ply")
                print(f"  Saved: {output_prefix}_posed.ply (scene coordinates)")

                scene_gs_normalized = ready_gaussian_for_video_rendering(
                    deepcopy(scene_gs), fix_alignment=True
                )
                scene_gs_normalized.save_ply(f"{output_prefix}.ply")
                print(f"  Saved: {output_prefix}.ply (normalized)")

                del scene_gs, scene_gs_normalized
                clear_gpu_memory()
        except torch.cuda.OutOfMemoryError:
            print("  OOM during Gaussian combination - skipping")
            clear_gpu_memory()

    # Create combined mesh scene
    print("\n[5/5] Combining meshes...")

    yup_to_zup = np.array([[1, 0, 0], [0, 0, 1], [0, -1, 0]], dtype=np.float32)

    scene_meshes_textured = []
    scene_meshes_colored = []

    for i, output in enumerate(outputs):
        if output.get("glb") is None:
            continue

        label = metadata['masks'][i]['label'] if i < len(metadata['masks']) else f"object_{i}"
        mesh = output["glb"]

        transformed_mesh = transform_mesh_preserve_visual(
            mesh,
            output["rotation"],
            output["translation"],
            output["scale"],
            yup_to_zup
        )
        scene_meshes_textured.append((f"{i:02d}_{label}", transformed_mesh))

        vertex_colors = sample_texture_to_vertex_colors(mesh)
        colored_mesh = trimesh.Trimesh(
            vertices=transformed_mesh.vertices.copy(),
            faces=transformed_mesh.faces.copy(),
            process=False
        )
        if vertex_colors is not None:
            colored_mesh.visual.vertex_colors = vertex_colors
        scene_meshes_colored.append(colored_mesh)

        clear_gpu_memory()
        print(f"  {i:02d}_{label}: {len(transformed_mesh.vertices)} vertices")

    # Save scene GLB
    if scene_meshes_textured:
        scene = trimesh.Scene()
        for name, mesh in scene_meshes_textured:
            scene.add_geometry(mesh, node_name=name)
        scene.export(f"{output_prefix}.glb")
        print(f"\n  Saved: {output_prefix}.glb ({len(scene_meshes_textured)} objects)")

    # Save merged OBJ
    if scene_meshes_colored:
        combined = merge_trimeshes(scene_meshes_colored)
        if combined is not None:
            combined.export(f"{output_prefix}.obj")
            print(f"  Saved: {output_prefix}.obj")

    print("\n" + "=" * 60)
    print("Scene reconstruction complete!")
    print("=" * 60)
    print(f"\nOutput files in {args.output_dir}/:")
    print(f"  scene.glb        - Textured meshes in camera space")
    print(f"  scene.ply        - Gaussian splat (normalized)")
    print(f"  scene_posed.ply  - Gaussian splat (camera space)")
    print(f"  objects_individual/ - Individual object files")


if __name__ == "__main__":
    main()
